name: treehacks_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '3.19.0'

dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  health: ^9.0.1
  pin_code_fields: ^8.0.1
  socket_io_client: ^2.0.3+1
  terra_flutter_bridge: ^0.6.3
  terra_flutter_rt: ^0.1.1
  web_socket_channel: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^9.0.0

flutter:
  uses-material-design: true
